export const SelectDifficulty = ["Any", "Easy", "Medium", "Hard"];

export const questions = [
  {
    question: "An algebraic expression containing three terms is called a",
    option1: "monomial",
    option2: "binomial",
    option3: "trinomial",
    option4: "all of these",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question:
      "Number of terms in the expression 3.x^2.y - 2.y^2.z - z^2.x + 5 is",
    option1: "2",
    option2: "3",
    option3: "4",
    option4: "5",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question: "The terms of expression 4.x^2 - 3.x.y are:",
    option1: "4.x^2 and -3.x.y",
    option2: "4.x^2 and 3.x.y",
    option3: "4.x^2 and -x.y",
    option4: "x^2 and x.y",
    correctOption: "1",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question: "Factors of -5.x^2.y^2.z are",
    option1: "-5.x.y.z",
    option2: "-5.x^2.y.z",
    option3: "-5.x.x.y.y.z",
    option4: "-5.x.y.z^2",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question: "Coefficient of x in -9.x.y^2.z is",
    option1: "9.y.z",
    option2: "-9.y.z",
    option3: "9.y^2.z",
    option4: "-9.y^2.z",
    correctOption: "4",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question: "The subtraction of 5 times of y from x is",
    option1: "5x - y",
    option2: "y - 5x",
    option3: "x - 5y",
    option4: "5y - x",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question:
      "The side length of the top of a square table is x. The expression for perimeter is:",
    option1: "4 + x",
    option2: "2x",
    option3: "4x",
    option4: "8x",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question:
      "The expression for the number of diagonals that we can make from one vertex of a n sided polygon is:",
    option1: "2n + 1",
    option2: "n - 2",
    option3: "5n + 2",
    option4: "n - 3",
    correctOption: "4",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
  {
    question: "123.x^2.y - 138.x^2.y is a like term of",
    option1: "10.x.y",
    option2: "-15.x.y",
    option3: "-15.x.y^2",
    option4: "10.x^2.y",
    correctOption: "4",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
  {
    question: "The value of 3.x^2 - 5.x + 3 when x = 1 is",
    option1: "1",
    option2: "0",
    option3: "-1",
    option4: "11",
    correctOption: "1",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question: "(2^20 ÷ 2^15) × 2^3 =",
    option1: "2^15",
    option2: "2^8",
    option3: "2^5",
    option4: "None of these",
    correctOption: "2",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
  {
    question: "(5/6)^0 =",
    option1: "1",
    option2: "6/5",
    option3: "0",
    option4: "None of these",
    correctOption: "1",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question: "(2^2)^n = (2^3)^4, then n =",
    option1: "4",
    option2: "3",
    option3: "12",
    option4: "6",
    correctOption: "4",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question: "(-7/5)^-1 =",
    option1: "5/7",
    option2: "-5/7",
    option3: "7/5",
    option4: "None of these",
    correctOption: "2",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question: "81^5 ÷ (3^2)^5 =",
    option1: "3^10",
    option2: "3^2",
    option3: "3^5",
    option4: "None of these",
    correctOption: "1",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question: "(8^2 × 8^4) - 2^18 =",
    option1: "2^2",
    option2: "2^4",
    option3: "0",
    option4: "None of these",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
  {
    question: "(3^7) ÷ (81 × 3^3) =",
    option1: "3",
    option2: "3^2",
    option3: "3^0",
    option4: "None of these",
    correctOption: "3",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
  {
    question: "(1/4)^-3 - (1/3)^-3 =",
    option1: "37",
    option2: "1/37",
    option3: "-37",
    option4: "-1/37",
    correctOption: "1",
    marksAllocated: 1,
    difficultyLevel: "Medium",
  },
  {
    question: "(10 × 5^(n+1)+ 25 × 5^n) ÷ (3 × 5^(n+2)+ 10 × 5^(n+1))",
    option1: "3/5",
    option2: "1",
    option3: "0",
    option4: "5",
    correctOption: "1",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
  {
    question: "(-1)^50 × (-1)^51 × (1)^100 × (-1)^101 =",
    option1: "-1",
    option2: "1",
    option3: "0",
    option4: "2",
    correctOption: "2",
    marksAllocated: 1,
    difficultyLevel: "Easy",
  },
  {
    question:
      "Find the mode for the data set, which shows the heights( in inches ) of 10 students in a class: 60, 65, 63, 62, 65, 70, 62, 68, 60, 65",
    option1: "62",
    option2: "65",
    option3: "70",
    option4: "60",
    correctOption: "2",
    marksAllocated: 1,
    difficultyLevel: "Hard",
  },
];
